baseurl: /kinhnghiemlaptrinh
url: https://ppap-1264589.github.io
theme: jekyll-theme-slate
title: Kinh nghiệm lập trình
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  algorithms:
    output: true

plugins:
  - jekyll-redirect-from